import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

function git(args) {
  try {
    return execSync(`git ${args}`, { encoding: "utf8", cwd: resolve(__dirname, "..") }).trim();
  } catch {
    return null;
  }
}

const commitCount = git("rev-list --count HEAD") ?? "0";
const shortHash = git("rev-parse --short HEAD") ?? "0000000";
const version = `1.0.0-build.${commitCount} (${shortHash})`;

const content = `// Auto-generated by scripts/gen-version.js — do not edit
export const appVersion = ${JSON.stringify(version)};
`;

writeFileSync(resolve(__dirname, "..", "src", "lib", "version.ts"), content, "utf8");
console.log(`[version] generated: ${version}`);
